news365/Controllers/ImageTablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using news365.Models;

namespace news365.Controllers
{
    public class ImageTablesController : Controller
    {
        private news365Entities db = new news365Entities();

        // GET: ImageTables


        public ActionResult Edit(int id = 2)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ImageTable imageTable = db.ImageTables.Find(id);
            if (imageTable == null)
            {
                return HttpNotFound();
            }
            return View(imageTable);
        }

        [HttpPost]
        //public ActionResult Edit([Bind(Include = "Img_id,Image,Text")] HttpPostedFileBase ImageFile)
        //{
            
        //    ImageTable setting = new ImageTable();

        //    try
        //    {

        //        string path = uploadimgfile(ImageFile);
        //        if (path.Equals("-1"))
        //        {
        //            ViewBag.error = "Image could not be uploaded....";
        //        }
        //        else
        //        {
        //            if (ModelState.IsValid)
        //            {
        //                string fileName = Path.GetFileNameWithoutExtension(setting.ImageFile.FileName);
        //                string extension = Path.GetExtension(setting.ImageFile.FileName);
        //                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
        //                setting.Image = "~/Image/" + fileName;
        //                fileName = Path.Combine(Server.MapPath("~/Image/"), fileName);
        //                setting.ImageFile.SaveAs(fileName);

        //                //db.Entry(setting).State = EntityState.Modified;
        //                //db.SaveChanges()

        //                //db.Entry(ImageFile).State = EntityState.Modified;
        //                //db.SaveChanges();
        //                //return RedirectToAction("Edit");
        //            }
        //            //return View();

        //            //    List<object> parameters = new List<object>();

        //            //    parameters.Add(path);
        //            //    parameters.Add(obj.Text);
        //            //parameters.Add(obj.Img_id);
        //            //    object[] objectarray = parameters.ToArray();

        //            //    int output = db.Database.ExecuteSqlCommand("update ImageTable set Image=@p0,Text=@p1 where Img_id=@p2", objectarray);
        //            //    if (output > 0)
        //            //    {
        //            //        ViewBag.Itemmsg = "Your profile is created seccussfully";
        //            //    }
        //        }


        //        return View();

        //    }
        //    catch
        //    {
        //        return View();
        //    }

        //}


        // Image uploading method
        public string uploadimgfile(HttpPostedFileBase file)
        {
            Random r = new Random();
            string path = "-1";
            int random = r.Next();
            if (file != null && file.ContentLength > 0)
            {
                string extension = Path.GetExtension(file.FileName);
                if (extension.ToLower().Equals(".jpg") || extension.ToLower().Equals(".jpeg") || extension.ToLower().Equals(".png"))
                {
                    try
                    {

                        path = Path.Combine(Server.MapPath("~/Images / "), random + Path.GetFileName(file.FileName));
                        file.SaveAs(path);
                        path = "~/imgfile/" + random + Path.GetFileName(file.FileName);

                        //    ViewBag.Message = "File uploaded successfully";
                    }
                    catch (Exception ex)
                    {
                        path = "-1";
                    }
                }
                else
                {
                    Response.Write("<script>alert('Only jpg ,jpeg or png formats are acceptable....'); </script>");
                }
            }

            else
            {
                Response.Write("<script>alert('Please select a file'); </script>");
                path = "-1";
            }

            return path;
        }

    }
}

news365/Views/ImageTables/Create.cshtml
@model news365.Models.ImageTable

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "ImageTables",FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>ImageTable</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <!--<div class="form-group">
        @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="ImageFile" required />-->
    @*@Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })*@
    <!--</div>
    </div>-->

    <div class="form-group">
        <div class="input-group">
            <label>Upload Image</label>
            <input type="file" name="imgfile" required />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

news365/Views/ImageTables/Delete.cshtml
@model news365.Models.ImageTable

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ImageTable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

news365/Views/ImageTables/Details.cshtml
@model news365.Models.ImageTable

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ImageTable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Img_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

news365/Views/ImageTables/Edit.cshtml
@model news365.Models.ImageTable

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "ImageTables", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ImageTable</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Img_id)

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageFile"  />
                @*@Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

news365/Views/ImageTables/Index.cshtml
@model IEnumerable<news365.Models.ImageTable>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Text)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Image)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Text)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Img_id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Img_id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Img_id })
        </td>
    </tr>
}

</table>