news365/Controllers/NewsTablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using news365.Models;

namespace news365.Controllers
{
    public class NewsTablesController : Controller
    {
        private news365Entities db = new news365Entities();

        // GET: NewsTables
        public ActionResult Index()
        {
            var newsTables = db.NewsTables.Include(n => n.CategoryTable);
            return View(newsTables.ToList());
        }


        public ActionResult NewsList(int id = 0)
        {
            NewsTable news = new NewsTable();
            using (news365Entities db = new news365Entities())
            {
                news.NewsCategories = db.CategoryTables.ToList<CategoryTable>();
            }

            return View(news);
        }
        [HttpPost]
        public ActionResult NewsList([Bind(Include = "NewsID,CategoryID,Description")] NewsTable newsTable)
        {

            if (ModelState.IsValid)
            {
                db.NewsTables.Add(newsTable);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(db.CategoryTables, "CategoryID", "CategoryName", newsTable.CategoryID);
            return View(newsTable);
        }





        // GET: NewsTables/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewsTable newsTable = db.NewsTables.Find(id);
            if (newsTable == null)
            {
                return HttpNotFound();
            }
            return View(newsTable);
        }

       
        // GET: NewsTables/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewsTable newsTable = db.NewsTables.Find(id);
            if (newsTable == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.CategoryTables, "CategoryID", "CategoryName", newsTable.CategoryID);
            return View(newsTable);
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "NewsID,CategoryID,Description")] NewsTable newsTable)
        {
            if (ModelState.IsValid)
            {
                db.Entry(newsTable).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.CategoryTables, "CategoryID", "CategoryName", newsTable.CategoryID);
            return View(newsTable);
        }

        // GET: NewsTables/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewsTable newsTable = db.NewsTables.Find(id);
            if (newsTable == null)
            {
                return HttpNotFound();
            }
            return View(newsTable);
        }

        // POST: NewsTables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NewsTable newsTable = db.NewsTables.Find(id);
            db.NewsTables.Remove(newsTable);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

news365/Views/NewsTables/Create.cshtml
@model news365.Models.NewsTable

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>NewsTable</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, "CategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

news365/Views/NewsTables/Delete.cshtml
@model news365.Models.NewsTable

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>NewsTable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategoryTable.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryTable.CategoryName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

news365/Views/NewsTables/Details.cshtml
@model news365.Models.NewsTable

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>NewsTable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategoryTable.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryTable.CategoryName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.NewsID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

news365/Views/NewsTables/Edit.cshtml
@model news365.Models.NewsTable

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>NewsTable</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.NewsID)

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, "CategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

news365/Views/NewsTables/Index.cshtml
@model IEnumerable<news365.Models.NewsTable>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "NewsList")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CategoryTable.CategoryName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CategoryTable.CategoryName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.NewsID }) |
            @Html.ActionLink("Details", "Details", new { id=item.NewsID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.NewsID })
        </td>
    </tr>
}

</table>

news365/Views/NewsTables/NewsList.cshtml
@model news365.Models.NewsTable

@{
    ViewBag.Title = "NewsList";
}

<h2>NewsList</h2>

@using (Html.BeginForm("NewsList", "NewsTables", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>NewsTable</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, "CategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CategoryID, new SelectList(Model.NewsCategories, "CategoryID", "CategoryName"), "Select")
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}